import { AppState } from './types'

const today = new Date().toISOString().split('T')[0]

export const mockState: AppState = {
  xp: 1850,
  energy: 4,
  weeklyReflection: 'Foi uma semana produtiva. Consegui focar nos objetivos principais.',
  tasks: [
    {
      id: '1',
      text: 'Finalizar relatório de Q3',
      area: 'work',
      priority: 'urgent',
      horizon: 'today',
      xp: 50,
      done: false,
      createdAt: today,
    },
    {
      id: '2',
      text: 'Treino de pernas',
      area: 'health',
      priority: 'high',
      horizon: 'today',
      xp: 20,
      done: true,
      createdAt: today,
    },
    {
      id: '3',
      text: 'Pagar conta de luz',
      area: 'finance',
      priority: 'normal',
      horizon: 'today',
      xp: 10,
      done: false,
      createdAt: today,
    },
    {
      id: '4',
      text: 'Ler 20 páginas',
      area: 'personal',
      priority: 'low',
      horizon: 'week',
      xp: 10,
      done: false,
      createdAt: today,
    },
    {
      id: '5',
      text: 'Planejar viagem',
      area: 'personal',
      priority: 'normal',
      horizon: 'month',
      xp: 50,
      done: false,
      createdAt: today,
    },
  ],
  habits: [
    {
      id: 'h1',
      name: 'Beber 2L de Água',
      emoji: '💧',
      color: '#10b981',
      history: { [today]: true, '2023-10-01': true, '2023-10-02': false },
    },
    {
      id: 'h2',
      name: 'Meditação',
      emoji: '🧘',
      color: '#7c6fff',
      history: { [today]: false },
    },
    {
      id: 'h3',
      name: 'Leitura',
      emoji: '📚',
      color: '#f0c040',
      history: { [today]: true },
    },
  ],
  goals: [
    { id: 'g1', title: 'Lançar MVP Dani OS', area: 'work', horizon: 'mensal', progress: 80 },
    { id: 'g2', title: 'Correr 5km', area: 'health', horizon: 'semanal', progress: 40 },
    { id: 'g3', title: 'Reserva de Emergência', area: 'finance', horizon: 'anual', progress: 65 },
    { id: 'g4', title: 'Aprender Espanhol', area: 'personal', horizon: 'anual', progress: 100 },
  ],
  transactions: [
    {
      id: 't1',
      description: 'Salário',
      category: 'Renda',
      amount: 5000,
      type: 'income',
      date: today,
    },
    {
      id: 't2',
      description: 'Aluguel',
      category: 'Moradia',
      amount: 1500,
      type: 'expense',
      date: today,
    },
    {
      id: 't3',
      description: 'Mercado',
      category: 'Alimentação',
      amount: 450,
      type: 'expense',
      date: today,
    },
  ],
  assets: [
    { id: 'a1', label: 'CDB Liquidez Diária', amount: 15000, color: '#fbbf24' },
    { id: 'a2', label: 'Ações BR', amount: 5000, color: '#10b981' },
  ],
}
